spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/devpub_db}
    username: root
    password: zzzzzzzz
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: devpub.system
    password: cppVnrbL7YDnZd8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

blog:
  title: "DevPub"
  subtitle: "Рассказы разработчиков"
  phone: "+7 999 111-22-33"
  email: "noob.online@yandex.ru"
  copyright: "Данила Шафранов"
  copyrightFrom: "2021"
  config:
    captchaSavePeriod : 3600