spring.datasource.url: jdbc:mysql://localhost:3306/devpub_db
spring.datasource.username: root
spring.datasource.password: "zzzzzzzz"

spring.jpa.hibernate.ddl-auto: none

blog.title: "DevPub"
blog.subtitle: "Рассказы разработчиков"
blog.phone: "+7 999 111-22-33"
blog.email: "noob.online@yandex.ru"
blog.copyright: "Данила Шафранов"
blog.copyrightFrom: "2021"